# Generated by Django 4.0.4 on 2022-05-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_alter_blogpost_content_blogpostuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogPost.blogpost')),
                ('commentar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.commentar')),
            ],
        ),
    ]
