# Generated by Django 4.0.4 on 2022-05-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_blogpostcommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='commentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.commentar'),
        ),
        migrations.AlterField(
            model_name='blogpostcommentar',
            name='commentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogPost.commentar'),
        ),
        migrations.AlterField(
            model_name='commentar',
            name='comm_content',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPostUser',
        ),
    ]
