# Generated by Django 4.0.4 on 2022-05-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_blogpost_commentar_alter_blogpostcommentar_commentar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcommentar',
            name='commentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.commentar'),
        ),
    ]
