# Generated by Django 4.0.4 on 2022-05-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0005_alter_blogpostcommentar_commentar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcommentar',
            name='blogPost',
        ),
        migrations.AddField(
            model_name='blogpostcommentar',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.user'),
        ),
        migrations.AlterField(
            model_name='commentar',
            name='comm_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
