# Generated by Django 4.0.4 on 2022-05-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0006_remove_blogpostcommentar_blogpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcommentar',
            name='blogPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.blogpost'),
        ),
    ]
