# Generated by Django 4.0.4 on 2022-05-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0007_blogpostcommentar_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='commentar',
        ),
        migrations.AddField(
            model_name='commentar',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.blogpost'),
        ),
    ]
