# Generated by Django 4.0.4 on 2022-05-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0009_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentar',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPost.user'),
        ),
    ]
