# Generated by Django 4.0.4 on 2022-05-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0010_commentar_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentar',
            name='author',
        ),
    ]
